---
version: '3.2'

networks:
  infra_default:
    external: true
  st_network:
    external: true

services:
  postgresql:
    image: postgres:9.6
    hostname: placeholder-postgresql
    networks:
      st_network:
        aliases:
          - placeholder-postgresql
    command: postgres -c max_connections=300
    environment:
      - POSTGRES_DB=placeholder
      - POSTGRES_USER=placeholder
      - POSTGRES_PASSWORD=placeholder
    restart: unless-stopped
    ports:
      - 5432:5432

  app:
    build:
      context: .
    command: ./manage.py runserver_plus 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    environment:
      - DB_NAME=placeholder
      - DB_USER=placeholder
      - DB_HOST=placeholder-postgresql
      - DB_PASSWORD=placeholder
      - DB_PORT=5432
      - DEBUG='true'
    restart: unless-stopped
    hostname: placeholder-app
    networks:
      infra_default:
        aliases:
          - placeholder-app
      st_network:
        aliases:
          - placeholder-app
    ports:
      - 8000:8000
    depends_on:
      - postgresql
